# Generated by Django 3.0.5 on 2020-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coffeemachines_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default='', max_length=70)),
                ('code', models.CharField(default='', max_length=200, unique=True)),
                ('coffee_flavor', models.CharField(default='', max_length=70)),
                ('pack_size', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='coffeemachines',
            name='code',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
