# Generated by Django 3.0.5 on 2020-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200915_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepods',
            name='coffee_flavor',
            field=models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'COFFEE_FLAVOR_VANILLA'), ('COFFEE_FLAVOR_CARAMEL', 'COFFEE_FLAVOR_CARAMEL'), ('COFFEE_FLAVOR_PSL', 'COFFEE_FLAVOR_PSL'), ('COFFEE_FLAVOR_MOCHA', 'COFFEE_FLAVOR_MOCHA'), ('COFFEE_FLAVOR_HAZELNUT', 'COFFEE_FLAVOR_HAZELNUT')], max_length=70),
        ),
        migrations.AlterField(
            model_name='coffeepods',
            name='pack_size',
            field=models.CharField(choices=[('1 dozen', '1 dozen'), ('3 dozen', '3 dozen'), ('5 dozen', '5 dozen'), ('7 dozen', '7 dozen')], max_length=70),
        ),
        migrations.AlterField(
            model_name='coffeepods',
            name='product_type',
            field=models.CharField(choices=[('COFFEE_POD_LARGE', 'COFFEE_POD_LARGE'), ('COFFEE_POD_SMALL', 'COFFEE_POD_SMALL'), ('ESPRESSO_POD', 'ESPRESSO_POD')], max_length=70),
        ),
    ]
